apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopflow.fullname" . }}
  labels: {{- include "shopflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "shopflow.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
